updated docs.gs sample
RajeshGogo/apps-script-samples pull request #1
Opened 2022-01-20 09:04 UTC by Priyankarp24

# Description

Updated advanced docs samples using ES6 feature 
Updated the Region tag.
Added try-catch 
Added comments

Fixes # 215484592

## Is it been tested?
- [X] Development testing done

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have performed a peer-reviewed with team member(s)
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2022-01-21 03:42 UTC, RajeshGogo commented
Get it review approved

2022-01-21 04:12 UTC, Manvendra-P-Singh approved these changes

2022-01-22 05:06 UTC, RajeshGogo requested changes
document.documentId => is used document without checking for null

2022-01-24 18:47 UTC, RajeshGogo approved these changes

2022-01-24 18:48 UTC, merged